# title of website
title: dh

# description of website
description: ydte's navigation site

# favicon of website
favicon: "https://github.com/ydte.png?size=40"

# your website url
url: https://ydte.github.io/dh/

# github profile url
github: "https://github.com/ydte"

# footer message
footer: © 2021-2021 @ydte

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

content:
  categories:
    - name: 常用推荐
      sites:
        - name: 导航
          description: 我的导航。
          url: http://www.ztz8.com/
    - name: 常访问的
      sites:
        - name: 第一个站
          description: 谷歌（推荐）
          url: https://www.google.com/
